### ISSUE TITLE
YOUR CLIENT ID what is ?

### ISSUE THREAD

**Issue by IAn2018cs** [jooyoungho/apple-token-revoke-in-firebase#1]
Hi, thanks for these.
but CLIENT ID where to get it ?

**Comment by jooyoungho** [comment]
Hello. @IAn2018cs 

TEAM ID, CLIENT ID, and KEY ID can all be found on the Apple site.

TEAM ID: Your team ID, which can be found at https://developer.apple.com/account/#!/membership.
CLIENT ID: For apps, this is your App ID (IDENTIFIER) located at https://developer.apple.com/account/resources/identifiers/list.
KEY ID: This is the Key ID that appears when you go to https://developer.apple.com/account/resources/authkeys/list.

**Comment by IAn2018cs** [comment]
> Hello. @IAn2018cs
> 
> TEAM ID, CLIENT ID, and KEY ID can all be found on the Apple site.
> 
> TEAM ID: Your team ID, which can be found at https://developer.apple.com/account/#!/membership. CLIENT ID: For apps, this is your App ID (IDENTIFIER) located at https://developer.apple.com/account/resources/identifiers/list. KEY ID: This is the Key ID that appears when you go to https://developer.apple.com/account/resources/authkeys/list.

Thanks !!!

**Comment by MikaloBlue** [comment]
@IAn2018cs 
Once we create this file on Apple and we change the XXXXXXXX part to the proper value, do we need to upload the p8 file somewhere so it finds it or is it able to get it from Apple again?
let privateKey = fs.readFileSync('AuthKey_XXXXXXXXXX.p8');

Thank you for this, it's helping greatly to try to get this feature in.

**Comment by jooyoungho** [comment]
@MikaloBlue 

You can deploy it by placing it in the same path as your Firebase Functions index.js file.  It is uploaded together when deploying.

**Comment by davidrazmadze** [comment]
## All required IDs

For `makeJWT()`, `getRefreshToken()`, and `revokeToken()`

**Comment by jooyoungho** [comment]
@davidrazmadze Thank you for your kind explanation. I'm concerned about seeing the Team ID in the screenshot. I recommend removing sensitive information such as team ID.

**Comment by davidrazmadze** [comment]
## All required IDs

For `makeJWT()`, `getRefreshToken()`, and `revokeToken()`

All of info can be found in the developer.apple.com portal. You will need the following: team id, client id, and key id.

## 1. Team ID

https://developer.apple.com/account/#!/membership

<img width="1163" alt="Screen Shot 2022-09-25 at 8 13 40 AM" src="https://user-images.githubusercontent.com/36372968/192142836-45752678-be69-4265-91e1-78ee0cb25939.png">

## 2. Client ID

This is the bundle identifier from your Xcode project or you can find it at https://developer.apple.com/account/resources/identifiers/list

<img width="1444" alt="Screen Shot 2022-09-23 at 8 09 37 PM" src="https://user-images.githubusercontent.com/36372968/192071342-7e76e1af-e6ea-45ed-8d2c-bcb46c39eb5f.png">

## 3. Key ID

You need to create a new key id and download the `.p8` private key file. Do not share this with anyone!

You can place the `.p8` file in the same directory as your firebase functions `/functions`

https://developer.apple.com/account/resources/authkeys/list

<img width="1270" alt="Screen Shot 2022-09-23 at 8 11 23 PM" src="https://user-images.githubusercontent.com/36372968/192071413-c3922e41-262b-41a8-8c34-f1a6fc632fba.png">
