### ISSUE TITLE
Receiving Status Code 500

### ISSUE THREAD

**Issue by ghost** [jooyoungho/apple-token-revoke-in-firebase#2]
Hi,

I have followed the instructions in the README and created the Firebase functions. I also applied my Client ID, Team ID, and Key ID. 

I am receiving status code 500. Any ideas for how to troubleshoot? 

`Optional(<NSHTTPURLResponse: 0x2811bf780> { URL: https://MY_DOMAIN.cloudfunctions.net/revokeToken?refresh_token=Error:%20could%20not%20handle%20the%20request%0A } { Status Code: 500, Headers {
    "Alt-Svc" =     (
        "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
    );
    "Content-Length" =     (
        36
    );
    "Content-Type" =     (
        "text/plain; charset=utf-8"
    );
    Date =     (
        "Sat, 25 Jun 2022 12:54:39 GMT"
    );
    Server =     (
        "Google Frontend"
    );
    "x-cloud-trace-context" =     (
        "7c07b9c035bebd4a7c6877f376005beb;o=1"
    );
    "x-content-type-options" =     (
        nosniff
    );
} })
`

**Comment by jooyoungho** [comment]
@andrejandre 
Hello, Is it possible to check the Log of Firebase Functions and not the console on iOS? I think there is a problem with the API communication with Apple. (If the log contains personal information, please delete it.)

**Comment by jooyoungho** [comment]
Also, it would be good to check if the refresh token is normally displayed through print(token) in the iOS console.

**Comment by ghost** [comment]
Thank you @jooyoungho 

It looks like one of my issues is that my Firebase functions are seeking the .p8 file

`Error: ENOENT: no such file or directory, open 'AuthKey_XXXXXXXXXX.p8'`

I think this is why I cannot see my token in iOS console, and also why I am receiving status code 500. Is the 'XXXXX....' part of the string supposed to be the client or key ID?

**Comment by ghost** [comment]
@jooyoungho  I see the instructions in the file. I just downloaded it and placed it in my directory. I will deploy my updated Firebase functions and let you know if my issue is resolved.

**Comment by ghost** [comment]
@jooyoungho  

You may close this issue. Adding my .p8 file to my firebase function project solved it! 

Thank you for your help & solution.

**Comment by jooyoungho** [comment]
@andrejandre  Glad the problem has been resolved :)

**Comment by jarrencampos** [comment]
*Leaving a note just in case anybody has the same issue as me. 

I highly recommend pulling up https://jooyoungho.github.io/apple-token-revoke-in-firebase/make-functions/ and following the steps that way. My issue was not providing the line below and I could not figure it out.

`npm install fs jsonwebtoken qs axios`

Thank you @jooyoungho for this resource!
