### ISSUE TITLE
Minor Improvement

### ISSUE THREAD

**Issue by ghost** [jooyoungho/apple-token-revoke-in-firebase#3]
When saving the apple refresh token,

If the developer wants to save in a ViewModel, they should do it like this:

`
DispatchQueue.main.async{
    UserDefaults.standard.set(refreshToken, forKey: "refreshToken")
    UserDefaults.standard.synchronize()
}
`

This is my suggestion to avoid application crashes, since it is possible that many developers may attempt to save this in a background thread if they are using the shared.dataTask in their ViewModel code.

**Comment by jooyoungho** [comment]
@andrejandre 

Thanks for the suggestion.
For security reasons, it's safer to store in Firestore than UserDefaults.  I will update the documentation.
