### ISSUE TITLE
How to create .p8 file

### ISSUE THREAD

**Issue by jtressle** [jooyoungho/apple-token-revoke-in-firebase#4]
Hi,

Thanks for the writeup.  If we don't have a .p8 file associated with Apple-Login, do we just create one using the page "Register a New Key"?

I have an existing .p8 file for notifications.  Is it best to add "Sign-In with Apple" to that one?  Or to create a brand new one?

Thanks

**Comment by jooyoungho** [comment]
@jtressle 
Hello. Up to three APNs keys can be issued, so it would be better to register a new key associated with the app to be used.
Make sure it is associated with the desired App ID in the configuration of Sign in with Apple. Also, please note that the key can only be downloaded once.

**Comment by jtressle** [comment]
@jooyoungho thanks for the clarification and quick answer!
