### ISSUE TITLE
Getting authorizationCode via reauthorization doesn't work 

### ISSUE THREAD

**Issue by jtressle** [jooyoungho/apple-token-revoke-in-firebase#5]
Hi,

Does the authorization code need to be the one the user first logged in with?  I'm trying to use the Firebase reauthorization workflow so I don't need to store the refresh token in KeyChain.  Does this not work?   

Here is my code:

`func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization)
    {
        if let appleIDCredential = authorization.credential as? ASAuthorizationAppleIDCredential
        {
            guard let nonce = currentNonce else {
                fatalError("Invalid state: A login callback was received, but no login request was sent.")
            }
            
            guard let appleIDToken = appleIDCredential.identityToken else {
                print ("Unable to fetch identity")
                return
            }
            
            guard let idTokenString = String(data: appleIDToken, encoding: .utf8) else {
                print("Unable to serialize token string from data: \(appleIDToken.debugDescription)")
                return
            }
            
            // Add new code below
            guard let authorizationCode = appleIDCredential.authorizationCode,
                  let codeString = String(data: authorizationCode, encoding: .utf8) else {
                print ("unable to get codeString")
                return
            }
            
            //initialize a firebase credential
            let credential = OAuthProvider.credential(withProviderID: "apple.com",
                                                      idToken: idTokenString,
                                                      rawNonce: nonce)
            
            //sign in with firebase
            Auth.auth().currentUser?.reauthenticate(with: credential) { [weak self] (authResult, error) in
                self?.getRefreshToken(codeString: codeString)
            }
        }
    }
`

Thanks again!

**Comment by jooyoungho** [comment]
@jtressle 
Unfortunately, I have not tested the reauthentication workflow in my documentation, it is intended for first time login authentication. It seems that you need to check whether Firebase's re-authentication process goes through the Apple sign-in authentication process.

**Comment by jtressle** [comment]
Thanks for the response.  I'm closing this issue as I got your code to work.  Great work again and thanks!
