### ISSUE TITLE
getRefreshToken

### ISSUE THREAD

**Issue by shubham-two** [jooyoungho/apple-token-revoke-in-firebase#6]
Im getting "Error: could not handle the request" for refresh token

**Comment by jooyoungho** [comment]
Hello, before sending the token, try to print to see if the token can be loaded properly.
I'm not sure about the details of the error, but check if the following parts are correct.
1. Whether the key information is correct when issuing JWT (You can check the functions log.)
2. Check if iOS can properly store and retrieve refresh tokens
3. Make sure you are calling the functions correctly

**Comment by yashmishra12** [comment]
Hey
Did you find a solution to this? I get the same error message for my refreshToken.

**Comment by yashmishra12** [comment]
**Refresh Token order:** 
let data = {
        'client_id': 'com.xxxxxxx.yyyyyy',
        'client_secret': client_secret,
        'code': code,
        'grant_type': 'authorization_code'
    }

**Revoke Token order:** 
    let data = {
        'client_id': 'com.xxxxxxx.yyyyyy',
        'client_secret': client_secret,
        'token': refresh_token,        
        'token_type_hint': 'refresh_token'
    };

I get no error, but I am still unable to get my apple token revoked.

**Comment by jooyoungho** [comment]
@shubham-two @yashmishra12 
You need to check that your code is properly laid out against the code generator.
https://jooyoungho.github.io/apple-token-revoke-in-firebase/make-functions/

**Comment by yashmishra12** [comment]
@jooyoungho If I follow the given data order (code, client_id, client_secret, grant_type), I get the same error as @shubham-two gets . After following Apple document's order, I no longer receive any error, but I am still unable to revoke apple token. Is there any way to connect with you to fix this?

**Comment by shubham-two** [comment]
I tried integrating this api using Swift I get invalid client error. I ran your your javascript code locally it works. I dont get error. but Iget the error only after deploying the firbase function.

**Comment by jooyoungho** [comment]
@shubham-two 

Is your key file inside your firebase project?  If it was run locally, check the location of the key file.

**Comment by shubham-two** [comment]
yes I put the p8 file in the same functions folder

**Comment by jooyoungho** [comment]
@shubham-two 

When I call functions, what error do I get in the firebase console?

**Comment by shubham-two** [comment]
<img width="1170" alt="Screen Shot 2022-07-18 at 9 58 20 AM" src="https://user-images.githubusercontent.com/107275383/179563686-fcd9d493-37d6-43db-a4fa-b9ecbcd23152.png">

**Comment by jooyoungho** [comment]
@shubham-two 

What code is on line 28:19 of the index.js file?  (If there is any security-related information, please delete it)

**Comment by shubham-two** [comment]
This is the code, same as yours. 

Line no 28: const qs = require('qs')

const functions = require('firebase-functions');

// The Firebase Admin SDK to access Firestore.
const admin = require('firebase-admin');
admin.initializeApp();
function makeJWT() {
    const jwt = require('jsonwebtoken')
    const fs = require('fs')
    // Path to download key file from developer.apple.com/account/resources/authkeys/list
    let privateKey = fs.readFileSync('AuthKey_xxxxxxxx.p8');
    //Sign with your team ID and key ID information.
    let token = jwt.sign({ 
    iss: 'xxxxxxx',
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 120,
    aud: 'https://appleid.apple.com',
    sub: 'xxxxxxx'
    }, privateKey, { 
    algorithm: 'ES256',
    header: {
    alg: 'ES256',
    kid: 'xxxxxxx',
    } });
    return token;
}
exports.getRefreshToken = functions.https.onRequest(async (request, response) => {
    //import the module to use
    const axios = require('axios');
    const qs = require('qs')
    const code = request.query.code;
    const client_secret = makeJWT();
    functions.logger.log("Client Secret", client_secret);
    let data = {
        'code': code,
        'client_id': 'xxxxxxxx',
        'client_secret': client_secret,
        'grant_type': 'authorization_code'
    }
    return axios.post('https://appleid.apple.com/auth/token', qs.stringify(data), {
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    })
    .then(async res => {
        const refresh_token = res.data;
        functions.logger.log("Response", res);
        response.send(res);
   
    });
});
exports.revokeToken = functions.https.onRequest( async (request, response) => {
    //import the module to use
    const axios = require('axios');
    const qs = require('qs');
    const refresh_token = request.query.refresh_token;
    const client_secret = makeJWT();
    let data = {
        'token': refresh_token,
        'client_id': 'xxxxxxxx',
        'client_secret': client_secret,
        'token_type_hint': 'refresh_token'
    };
    return axios.post('https://appleid.apple.com/auth/revoke', qs.stringify(data), {
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
    })
    .then(async res => {
        console.log(res.data);
    });
});

**Comment by jooyoungho** [comment]
@shubham-two 
Hi, I would like to help, but the information I can get is limited.

First of all, check the following:
1. Check the data object of getRefreshToken with the console to check whether code and client_id are output properly.
2. Check if npm install qs in the functions folder is correct. (You may want to check other packages as well)
3. Check that the TEAM ID, CLIENT ID, and KEY ID are entered correctly.

*TEAM ID: Your team ID, which can be found at https://developer.apple.com/account/#!/membership.
CLIENT ID: For apps, this is your App ID (IDENTIFIER) located at https://developer.apple.com/account/resources/identifiers/list.
KEY ID: This is the Key ID that appears when you go to https://developer.apple.com/account/resources/authkeys/list.

**Comment by yashmishra12** [comment]
Hi @jooyoungho 
I ran your code by fixing two things: 
1. Updated my Node from v14 to v16. 
2. Added a two-second delay to removeAccount function call after the refresh token has been set to UserDefault. 

Thank you so much for your code.

**Comment by shubham-two** [comment]
Hey I used an alternative approach I integrated the apple APIs using alamofire in swift. @jooyoungho thank you for providing this approach. I'm closing this issue. 
Swift Code: 
let params = [
                "code": "XXXXXX",
                "client_id": "XXXXXX",
                "client_secret": "XXXXX",
                "grant_type": "authorization_code"
            ]
            AF.request(URL(string: "https://appleid.apple.com/auth/token")!, method: .post, parameters: params, encoding: URLEncoding.default, headers: ["Content-Type": "application/x-www-form-urlencoded"]).responseJSON {
                [weak self]
                response in
                switch response.result {
                case .success :
                    //parse the response for fetching refresh token
                    break
                case .failure :
                        
                    break
                default:
                    break
                }
